---

- name: install key
  apt_key: keyserver='keyserver.ubuntu.com' id='0C54D189F4BA284D'

- name: install repository
  apt_repository: repo='deb https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-ubuntu1804 ./'

- name: install package
  package: name='code-brand'
  with_items:
    - 'loolwsd'
    - 'code-brand'

- name: enable service
  service: name='loolwsd' state='started' enabled=true

- name: deploy website
  template: dest='/etc/nginx/sites-available/collabora.cnf' src='templates/nginx.cnf.j2'
  notify: reload nginx

- name: enable website
  file: path='/etc/nginx/sites-enabled/collabora.cnf' src='/etc/nginx/sites-available/collabora.cnf' state='link'
  notify: reload nginx

  # https://morph027.gitlab.io/post/collabora-online-without-docker/
