---

- name: create datauser
  postgresql_user: name='prosody' password='{{prosody_database_pass}}' role_attr_flags='CREATEDB' encrypted=true
  become_user: 'postgres'

- name: create database
  postgresql_db: name='prosody' owner='prosody'
  become_user: 'postgres'
